### PR TITLE
add Items() to return all items as map[string]interface{}

### PR DESCRIPTION
**Pull request by sillydong**
for convenient to get items

### CODE REVIEW

**Comment by eranchetz** [comment]
@sillydong great work! Can you please add a test case, and I will merge it?

thanks a lot.

**Comment by sillydong** [comment]
I have added test func for Items(), please check it.
Thx!

**Comment by eranchetz** [comment]
```
go test -run Items
PASS
ok  	_/tmp/concurrent-map	0.006s
```
 LGTM 
Merging

**Comment by sillydong** [comment]
thanks

**Pull request merged**
