### PR TITLE
Add aux lock to ConcurrentMapShared struct

### PR DESCRIPTION
**Pull request by stgleb**
that allows nested locking for read-modify-update.

### CODE REVIEW

**Comment by eranchetz** [comment]
@stgleb thanks a lot!
Can you please add it to the template as well?

**Comment by stgleb** [comment]
Yep, i will

**Comment by eranchetz** [comment]
Thanks

**Comment by eranchetz** [comment]
@stgleb A kind reminder

**Comment by eranchetz** [comment]
@stgleb sorry for the delay, why would we need an aux lock here? can you give and example?
thanks

**Comment by eranchetz** [comment]
https://github.com/streamrail/concurrent-map/pull/27 solves this as well

**Pull request closed without merging**
